### ISSUE TITLE
Discord can scan this repo

### ISSUE THREAD

**Issue by wasvr** [tdsoperational/discord-rat-tokens#3]
I just found out that discord has a token scanner, it goes around on the internet and if it finds your bot token, it resets it, maybe make this repo a bit more secure: https://github.com/tdsoperational/discord-rat-tokens/assets/154990925/99868dee-23f5-47b8-819a-00db98611d0e

**Comment by tdsoperational** [comment]
Thats the goddamn point of this repo 🤯
