### ISSUE TITLE
One of my bot token was leaked

### ISSUE THREAD

**Issue by 1tbfree** [tdsoperational/discord-rat-tokens#4]
Is it fine? Idk how did you guys get it. I used it for pentesting only. I even connected literally nothing

**Comment by tdsoperational** [comment]
I don't see how you use a remote administration tool for "Pentesting". 
I will proceed to disrupt this here.

Sincerely, tdsoperational

**Comment by 1tbfree** [comment]
I was using it to test Discord RAT. also I only putted VMs here not real PCs

**Comment by 1tbfree** [comment]
I did not need it anyways. It was bugging, idk why. Also how did you find the token?

**Comment by tdsoperational** [comment]
Multiple sources, the process is automated so i cannot directly tell.
Sincerely, tdsmental

**Comment by 1tbfree** [comment]
Oh. Maybe its because I uploaded it to virustotal?

**Comment by tdsoperational** [comment]
Likely not.

**Comment by 1tbfree** [comment]
Did you also check the bot username and stuff? My bot username didn't have anything private anyways

**Comment by tdsoperational** [comment]
It is a automated process, so no i do not read usernames, or similar. 
This isn't just you here, any sample that is suspected to be live, will be put into this repo.
Sincerely, tdsmental
